repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: detect-private-key
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args:
          - "--check"
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -  id: codespell
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        additional_dependencies: [numpy >= 1.22.1, casadi >= 3.5.5, requests >= 2.22.0, types-requests >= 2.28.11.2 ]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
    -   id: validate-html
        args: [--remove-mustaches, --mustache-remover=jinja2]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types_or: [css, javascript, markdown]
