site_name: Temperature Server

theme:
  name: "material"
  features:
    - navigation.tracking

repo_url: https://github.com/PeterHofmeier/crane_simulator

plugins:
  - search
  - bibtex:
      bib_dir: "docs/bib/"
      csl_file: "docs/bib/ieee.csl"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            heading_level: 2
            show_root_toc_entry: false
            show_root_full_path: false
            show_if_no_docstring: true
          selection:
            new_path_syntax: true
            filters:
              - "!^_"  # exclude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: 'index.md'
