name: pre-commit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --show-diff-on-failure --all-files
